name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.5.6
          run_install: |
            recursive: true

      - name: Build
        run: pnpm build -r
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Test
        run: pnpm test -r
        env:
          SHOW_SPAWN_CMD: true
          CI: true
